[custom.all.array]
type   = "local"
path   = "."
ipkg   = "array.ipkg"
test   = "test/test.ipkg"

[custom.all.array-docs]
type   = "local"
path   = "docs"
ipkg   = "docs.ipkg"

[custom.all.ref1]
type   = "git"
url    = "git@github.com:stefan-hoeck/idris2-ref1"
commit = "latest:main"
ipkg   = "ref1.ipkg"
